/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.sbd12.sewamobil.Utama;




import java.util.logging.Level;
import java.util.logging.Logger;

import java.util.List;
import javax.swing.JOptionPane;
import org.springframework.context.ApplicationContext;
import org.springframework.context.support.ClassPathXmlApplicationContext;
import com.sbd12.sewamobil.Pkg_Merk_Mobil.*;
import com.sbd12.sewamobil.Pkg_ProdusenMobil.*;
import com.sbd12.sewamobil.Pkg_Data_Mobil.*;
import com.sbd12.sewamobil.Pkg_Jenis_Mobil.*;
import com.sbd12.sewamobil.Pkg_Data_Transaksi.*;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.sql.Date;
import org.joda.time.DateTime;
import org.joda.time.Days;

/**
 *
 * @author ArieDZ 2
 */
public class panel_data_transaksi extends javax.swing.JPanel {

    /**
     * Creates new form panel_data_barang
     */
    public DataTransaksiTableModel tableTransaksi;
    
    public frm_Utama_metro form_parent;
    
    public List<JenisMobil> jeniss;
    public List<ProdusenMobil> produsens ;
    public List<MerkMobil> merk_Mobils ;
    public List<DataMobil> data_mobil;
    public List<DataTransaksi> dataTransaksis;
    
    public DataTransaksiJDBCTemplate db;

    public panel_data_transaksi() throws ClassNotFoundException {
        initComponents();
        ApplicationContext context = new ClassPathXmlApplicationContext("Config-Spring.xml");
         db = (DataTransaksiJDBCTemplate)
                context.getBean("dataTransaksiJDBCTemplate");


        dataTransaksis = db.listSemua();
        
        
           jTable1.addMouseListener(new MouseAdapter() {
            @Override
            public void mousePressed(MouseEvent e) {
                if (e.getClickCount() >= 1) {
                    int baris = jTable1.getSelectedRow();
                    String no_transaksi = (String) tableTransaksi.getValueAt(baris, 0);
                    System.out.println("Klik di Table = id =" + no_transaksi);
                    DataTransaksi mm =db.pilih_data(no_transaksi);
                    tf_no_transaksi.setText(mm.getNo_transaksi());
                    tf_nama_kostumer.setText(mm.getNama_kostumer());
                    Date date1 = mm.getTglpinjam();
                    Date date2 = mm.getTglkembali();
                    jDate_tglpinjam.setDate(date1);
                    jDate_tglkembali.setDate(date2);
                    tf_no_pol.setText(mm.getNo_pol());
                    tf_harga_total.setText(String.valueOf(mm.getHarga_total()));
                    
                    DateTime dateTime1 = new DateTime(date1);
                    DateTime dateTime2 = new DateTime(date2);
                    int days = Days.daysBetween(dateTime1, dateTime2).getDays();
                    
                    tf_lama_pinjam1.setText(String.valueOf(days)+"-Hari");
                    /*tf_id_merk.setText(mm.getId_merk_mobil());
                    jCb_produsen.setSelectedItem(mm.getNama_produsen_mobil());
                    jCb_jenis.setSelectedItem(mm.getNama_jenis());
                    tf_nama_merk.setText(mm.getNama_Merk_Mobil()); */
                
                
                }
            }
        });
           
        tampilData_Transaksi();
        
        refreshData();
    }
    
    public void tampilData_Transaksi() throws ClassNotFoundException
    {

        tableTransaksi = new DataTransaksiTableModel();
        tableTransaksi.setData(dataTransaksis);
        jTable1.setModel(tableTransaksi);

    }


    public void refreshData() throws ClassNotFoundException
    {   
        dataTransaksis = db.listSemua();
        tableTransaksi.setData(dataTransaksis);
        tableTransaksi.fireTableDataChanged();
        jTable1.changeSelection(0, 0, false, false);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        BtTambah = new javax.swing.JButton();
        BtEdit = new javax.swing.JButton();
        BtHapus = new javax.swing.JButton();
        BtRefresh = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        tf_no_transaksi = new javax.swing.JTextField();
        tf_no_pol = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jCb_nama_pegawai = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        tf_nama_kostumer = new javax.swing.JTextField();
        jComboBox2 = new javax.swing.JComboBox<>();
        jComboBox3 = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        tf_harga_total = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jDate_tglpinjam = new com.toedter.calendar.JDateChooser();
        jLabel4 = new javax.swing.JLabel();
        jDate_tglkembali = new com.toedter.calendar.JDateChooser();
        jLabel5 = new javax.swing.JLabel();
        tf_lama_pinjam1 = new javax.swing.JTextField();
        BtCari = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(960, 510));

        bg.setBackground(new java.awt.Color(204, 204, 204));
        bg.setPreferredSize(new java.awt.Dimension(960, 510));

        jScrollPane1.setOpaque(false);
        jScrollPane1.setPreferredSize(new java.awt.Dimension(768, 331));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        BtTambah.setText("Tambah");
        BtTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtTambahActionPerformed(evt);
            }
        });

        BtEdit.setText("Edit");
        BtEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtEditActionPerformed(evt);
            }
        });

        BtHapus.setText("Hapus");
        BtHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtHapusActionPerformed(evt);
            }
        });

        BtRefresh.setText("Refresh");
        BtRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtRefreshActionPerformed(evt);
            }
        });

        jLabel2.setText("No Transaksi");

        tf_no_transaksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_no_transaksiActionPerformed(evt);
            }
        });

        tf_no_pol.setEditable(false);

        jLabel3.setText("Nama Konstumer");

        jLabel1.setText("Nama Pegawai");

        jCb_nama_pegawai.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel6.setText("Mobil");

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel7.setText("Lama Pinjam");

        tf_harga_total.setEditable(false);

        jLabel8.setText("Tanggal Pinjam");

        jLabel4.setText("Tanggal Kembali");

        jLabel5.setText("Harga Total");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tf_no_transaksi)
                            .addComponent(jCb_nama_pegawai, 0, 150, Short.MAX_VALUE)
                            .addComponent(tf_nama_kostumer)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel4))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jDate_tglpinjam, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jDate_tglkembali, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addComponent(tf_lama_pinjam1, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)))))
                .addGap(57, 57, 57)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(47, 47, 47)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jComboBox2, 0, 150, Short.MAX_VALUE)
                    .addComponent(jComboBox3, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tf_no_pol)
                    .addComponent(tf_harga_total))
                .addContainerGap(204, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(tf_no_transaksi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(tf_nama_kostumer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jCb_nama_pegawai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(tf_harga_total, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel5)
                                .addComponent(tf_lama_pinjam1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jDate_tglpinjam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(jLabel4))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jDate_tglkembali, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(tf_no_pol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(44, Short.MAX_VALUE))
        );

        BtCari.setText("Cari");
        BtCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtCariActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout bgLayout = new javax.swing.GroupLayout(bg);
        bg.setLayout(bgLayout);
        bgLayout.setHorizontalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BtTambah)
                    .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(BtEdit, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BtHapus, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BtRefresh, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(BtCari, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(bgLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(85, Short.MAX_VALUE))
        );
        bgLayout.setVerticalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bgLayout.createSequentialGroup()
                        .addComponent(BtTambah)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BtEdit)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BtHapus)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BtRefresh)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BtCari))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bg, 948, 948, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bg, javax.swing.GroupLayout.PREFERRED_SIZE, 543, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void BtTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtTambahActionPerformed
        // TODO add your handling code here:
         System.out.println("Menekan Tombol Tambah");
         
       String nama_produsenPilih = jCb_produsen.getSelectedItem().toString();
       String id_produsenPilih = "-";
       String nama_jenisPilih = jCb_jenis.getSelectedItem().toString();
       String id_jenisPilih="-";
       
       if((!nama_jenisPilih.equalsIgnoreCase("Pilih"))&&(!nama_produsenPilih.equalsIgnoreCase("Pilih"))){
       for(ProdusenMobil produsenMobil:produsens)
       {
           if (produsenMobil.getNama_produsen().equals(nama_produsenPilih))
           {
               id_produsenPilih=produsenMobil.getId_produsen();
           }
       }
       for(JenisMobil jenisMobil:jeniss)
       {
           if (jenisMobil.getNama_jenis_mobil().equals(nama_jenisPilih))
           {
               id_jenisPilih=jenisMobil.getId_jenis_mobil();
           }
       }
       
       System.out.println("nama : "+nama_produsenPilih+" id : "+id_produsenPilih);
       System.out.println("nama : "+nama_jenisPilih+" id : "+id_jenisPilih);
       merk_mobilJDBCTemplate.create(tf_no_transaksi.getText(), id_produsenPilih, id_jenisPilih, tf_no_pol.getText());
       }
       else{
           System.out.println("Dihentikan -ComboBox produsen:"+nama_produsenPilih+", -ComboBox Jenis:"+nama_jenisPilih);
        }
       
      
        try {
            refreshData();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(panel_merk_mobil.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_BtTambahActionPerformed

    private void BtEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtEditActionPerformed
            System.out.println("Menekan tombol edit");
            
            int baris = jTable1.getSelectedRow();
       String id=(String)tableMerk.getValueAt(baris, 0);            
       String nama_produsenPilih = jCb_produsen.getSelectedItem().toString();
       String id_produsenPilih = "-";
       String nama_jenisPilih = jCb_jenis.getSelectedItem().toString();
       String id_jenisPilih="-";
       
       if((!nama_jenisPilih.equalsIgnoreCase("Pilih"))&&(!nama_produsenPilih.equalsIgnoreCase("Pilih"))){
       for(ProdusenMobil produsenMobil:produsens)
       {
           if (produsenMobil.getNama_produsen().equals(nama_produsenPilih))
           {
               id_produsenPilih=produsenMobil.getId_produsen();
           }
       }
       for(JenisMobil jenisMobil:jeniss)
       {
           if (jenisMobil.getNama_jenis_mobil().equals(nama_jenisPilih))
           {
               id_jenisPilih=jenisMobil.getId_jenis_mobil();
           }
       }
       merk_mobilJDBCTemplate.edit(tf_no_transaksi.getText(), id_produsenPilih, id_jenisPilih, tf_no_pol.getText());
        }
       
        try {
            refreshData();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(panel_merk_mobil.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_BtEditActionPerformed

    private void BtHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtHapusActionPerformed
        // TODO add your handling code here:

        
            int baris = jTable1.getSelectedRow();
            String id=(String)tableMerk.getValueAt(baris, 0);
            merk_mobilJDBCTemplate.delete(id);
            System.out.println("Menekan tombol hapus");
            System.out.println(id);
           /* Object[] pilihan ={"Ya","Tidak"};
            int jawaban= JOptionPane.showOptionDialog(null, "Anda yakin data "
                +"Barang dengan Kode"+nim+" dengan nama Barang "+nama+" akan"
                +"dihapus? ","Peringatan",JOptionPane.DEFAULT_OPTION,
                JOptionPane.WARNING_MESSAGE,null,pilihan,pilihan[0]);
            if(jawaban==0)
            {
                
            }*/
        try {
            refreshData();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(panel_merk_mobil.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_BtHapusActionPerformed

    private void BtRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtRefreshActionPerformed
        try {
            // TODO add your handling code here:
            refreshData();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(panel_merk_mobil.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_BtRefreshActionPerformed

    private void BtCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtCariActionPerformed
        // TODO add your handling code here:
        String katakunci;
        katakunci=JOptionPane.showInputDialog(null,"Nama barang yang di cari?","Filter/Pencarian",JOptionPane.QUESTION_MESSAGE);
        if(katakunci!=null)
        {
            merk_Mobils =  merk_mobilJDBCTemplate.pilih_data_like(katakunci);
            tableMerk.setData(merk_Mobils);
            tableMerk.fireTableDataChanged();
            jTable1.changeSelection(0, 0, false, false);
        }
    }//GEN-LAST:event_BtCariActionPerformed

    private void tf_no_transaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_no_transaksiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_no_transaksiActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtCari;
    private javax.swing.JButton BtEdit;
    private javax.swing.JButton BtHapus;
    private javax.swing.JButton BtRefresh;
    private javax.swing.JButton BtTambah;
    private javax.swing.JPanel bg;
    private javax.swing.JComboBox<String> jCb_nama_pegawai;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private com.toedter.calendar.JDateChooser jDate_tglkembali;
    private com.toedter.calendar.JDateChooser jDate_tglpinjam;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField tf_harga_total;
    private javax.swing.JTextField tf_lama_pinjam1;
    private javax.swing.JTextField tf_nama_kostumer;
    private javax.swing.JTextField tf_no_pol;
    private javax.swing.JTextField tf_no_transaksi;
    // End of variables declaration//GEN-END:variables
}
