/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.sbd12.sewamobil.Pkg_Data_Transaksi;

import com.sbd12.sewamobil.Pkg_Data_Mobil.DataMobil;
import com.sbd12.sewamobil.Pkg_Data_Mobil.DataMobilJDBCTemplate;
import com.sbd12.sewamobil.Pkg_Data_Mobil.DataMobilTableModel;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListSelectionModel;
import javax.swing.ListSelectionModel;
import org.springframework.context.ApplicationContext;
import org.springframework.context.support.ClassPathXmlApplicationContext;

/**
 *
 * @author ArieDZ_2
 */
public class FD_Barang extends javax.swing.JDialog {

    /**
     * Creates new form FD_Tampil_Kostumer
     */
    public List<DataMobil> dataMobils;
    public DataMobilJDBCTemplate db;
    public DataMobilTableModel tableDataMobil;
    public DetailTransaksiTableModel detailTransaksiTableModel;
    public ArrayList<String> list = new ArrayList<>();
    public String list_barang = "";
    private double harga_total = 0;

    public FD_Barang(java.awt.Frame parent, boolean modal) throws ClassNotFoundException {
        super(parent, modal);
        initComponents();
        ApplicationContext context = new ClassPathXmlApplicationContext("Config-Spring.xml");
        db = (DataMobilJDBCTemplate) context.getBean("dataMobilJDBCTemplate");
        dataMobils = db.listSemua();

        tampilData();
        refreshData();
    }

    public FD_Barang(java.awt.Frame parent, boolean modal, String orderId) throws ClassNotFoundException {
        super(parent, modal);
        initComponents();
        ApplicationContext context = new ClassPathXmlApplicationContext("Config-Spring.xml");
        db = (DataMobilJDBCTemplate) context.getBean("dataMobilJDBCTemplate");
        dataMobils = db.listSemua_berdasar_noTransaksi(orderId);
        jb_pilih.setVisible(false);

        tampilData(orderId);
        refreshData(orderId);
    }

    public double getHarga_total() {
        return harga_total;
    }

    public void setHarga_total(double harga_total) {
        this.harga_total = harga_total;
    }

    public ArrayList<String> getList() {
        return list;
    }

    public void setList(ArrayList<String> list) {
        this.list = list;
    }

    public String getList_barang() {
        return list_barang;
    }

    public void setList_barang(String list_barang) {
        this.list_barang = list_barang;
    }

    public void setTabel(String orderId) throws ClassNotFoundException {
        tampilData(orderId);
        refreshData(orderId);
    }

    public void tampilData(String orderId) throws ClassNotFoundException {

        detailTransaksiTableModel = new DetailTransaksiTableModel();
        detailTransaksiTableModel.setData(dataMobils);
        jTable1.setModel(detailTransaksiTableModel);

    }

    public void refreshData(String orderId) throws ClassNotFoundException {
        dataMobils = db.listSemua_berdasar_noTransaksi(orderId);
        detailTransaksiTableModel.setData(dataMobils);
        detailTransaksiTableModel.fireTableDataChanged();
        jTable1.changeSelection(0, 0, false, false);
    }

    public void tampilData() throws ClassNotFoundException {

        tableDataMobil = new DataMobilTableModel();
        tableDataMobil.setData(dataMobils);
        jTable1.setModel(tableDataMobil);

    }

    public void refreshData() throws ClassNotFoundException {
        dataMobils = db.listSemua();
        tableDataMobil.setData(dataMobils);
        tableDataMobil.fireTableDataChanged();
        jTable1.changeSelection(0, 0, false, false);
    }

    public class ForcedListSelectionModel extends DefaultListSelectionModel {

        public ForcedListSelectionModel() {
            setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        }

        @Override
        public void clearSelection() {
        }

        @Override
        public void removeSelectionInterval(int index0, int index1) {
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg_panel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jb_pilih = new javax.swing.JButton();
        tf_cari = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        bg_panel.setBackground(new java.awt.Color(255, 255, 255));
        bg_panel.setForeground(new java.awt.Color(255, 255, 255));

        jScrollPane1.setOpaque(false);
        jScrollPane1.setPreferredSize(new java.awt.Dimension(768, 331));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jb_pilih.setText("Pilih");
        jb_pilih.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_pilihActionPerformed(evt);
            }
        });

        jButton1.setText("Cari");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout bg_panelLayout = new javax.swing.GroupLayout(bg_panel);
        bg_panel.setLayout(bg_panelLayout);
        bg_panelLayout.setHorizontalGroup(
            bg_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bg_panelLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 560, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jb_pilih, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(bg_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tf_cari, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        bg_panelLayout.setVerticalGroup(
            bg_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bg_panelLayout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addGroup(bg_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_cari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(bg_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jb_pilih)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(bg_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jb_pilihActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_pilihActionPerformed
        // TODO add your handling code here:
        int[] selectedrows = jTable1.getSelectedRows();

        ArrayList<String> list = new ArrayList<>();
        if (selectedrows.length == -1) {
            list_barang = "Harus Pilih Barang";
        } else {
            for (int i = 0; i < selectedrows.length; i++) {

                String kode = tableDataMobil.getValueAt(selectedrows[i], 0).toString();
                String nama = tableDataMobil.getValueAt(selectedrows[i], 1).toString();
                this.harga_total += (Double) tableDataMobil.getValueAt(selectedrows[i], 3);
                list.add(kode);
                list_barang += "-" + kode + " -" + nama + "\n";
                System.out.println(kode);
            }

            setList(list);
        }

        setList_barang(list_barang);
        setVisible(false);

    }//GEN-LAST:event_jb_pilihActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        if (!tf_cari.getText().isEmpty()) {

            dataMobils = db.pilih_data_like(tf_cari.getText());
            tableDataMobil.setData(dataMobils);
            tableDataMobil.fireTableDataChanged();
            jTable1.changeSelection(0, 0, false, false);
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FD_Tampil_Kostumer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FD_Tampil_Kostumer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FD_Tampil_Kostumer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FD_Tampil_Kostumer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(() -> {
            FD_Tampil_Kostumer dialog = null;
            try {
                dialog = new FD_Tampil_Kostumer(new javax.swing.JFrame(), true);
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(FD_Barang.class.getName()).log(Level.SEVERE, null, ex);
            }
            dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                @Override
                public void windowClosing(java.awt.event.WindowEvent e) {
                    System.exit(0);
                }
            });
            dialog.setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bg_panel;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton jb_pilih;
    private javax.swing.JTextField tf_cari;
    // End of variables declaration//GEN-END:variables
}
